### PR TITLE
Add remote to PyPi

### LINKED ISSUE #18: Upload to PyPi
believe it or not, there is not remote package in PyPi

### PR DESCRIPTION
**Pull request by nsorros**
Fixes #18 

⚠️ Remote rename needs to merge first. Also the package has not been uploaded yet, we need to agree if we will use Mantis account or you want to create an account to upload it under your username.

### CODE REVIEW

**Comment by ivyleavedtoadflax** [comment]
It would be good to fix a few of the bugs i have been storing up in issues before doing this. Also I was wondering about changing the API to be more like:
```
# start instance
remote instance start 

# List snapshots
remote snapshot list

# List AMIs
remote ami create
```
Basically since i started to add some of this other functionality, it feels like it should be using subcommands

**Comment by ivyleavedtoadflax** [comment]
:point_up: see #22

**Comment by nsorros** [comment]
Can we list which issues need to be addressed before this can go forward @ivyleavedtoadflax. This way I can start working on them.

**Comment by nsorros** [comment]
Closing for now, happy to reopen when we want to publish

**Pull request closed without merging**
